---
import_mode: Batch - Directory Only
base_directory: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Viewer-Demo-Results
file_configs:
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Viewer-Demo-Results/exam1.inp
  network_name: exam1
  file_basename: exam1.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Viewer-Demo-Results/extran1.inp
  network_name: extran1
  file_basename: extran1.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Viewer-Demo-Results/extran10.inp
  network_name: extran10
  file_basename: extran10.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Viewer-Demo-Results/extran2.inp
  network_name: extran2
  file_basename: extran2.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Viewer-Demo-Results/extran3.inp
  network_name: extran3
  file_basename: extran3.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Viewer-Demo-Results/extran4.inp
  network_name: extran4
  file_basename: extran4.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Viewer-Demo-Results/extran5.inp
  network_name: extran5
  file_basename: extran5.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Viewer-Demo-Results/extran6.inp
  network_name: extran6
  file_basename: extran6.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Viewer-Demo-Results/extran7.inp
  network_name: extran7
  file_basename: extran7.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Viewer-Demo-Results/extran8a.inp
  network_name: extran8a
  file_basename: extran8a.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Viewer-Demo-Results/extran8b.inp
  network_name: extran8b
  file_basename: extran8b.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Viewer-Demo-Results/extran9.inp
  network_name: extran9
  file_basename: extran9.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Viewer-Demo-Results/user1.inp
  network_name: user1
  file_basename: user1.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Viewer-Demo-Results/user2_slot.inp
  network_name: user2_slot
  file_basename: user2_slot.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Viewer-Demo-Results/user3.inp
  network_name: user3
  file_basename: user3.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Viewer-Demo-Results/user4.inp
  network_name: user4
  file_basename: user4.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Viewer-Demo-Results/user5_slot.inp
  network_name: user5_slot
  file_basename: user5_slot.inp
import_group_id: 1
import_group_name: owa
cleanup_empty_label_lists: true
validate_after_import: true
run_icm_validation: true
commit_even_if_invalid: false
create_infoworks_shells: true
shell_name_suffix: ''
