---
import_mode: Batch - Directory Only
base_directory: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Orifices
file_configs:
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Orifices/bottom_vs_side_orifice_test.inp
  network_name: bottom_vs_side_orifice_test
  file_basename: bottom_vs_side_orifice_test.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Orifices/extran3_bottom_orifice.inp
  network_name: extran3_bottom_orifice
  file_basename: extran3_bottom_orifice.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Orifices/extran3_bottom_orifice_pid.inp
  network_name: extran3_bottom_orifice_pid
  file_basename: extran3_bottom_orifice_pid.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Orifices/extran3_bottom_orifice_si_units.inp
  network_name: extran3_bottom_orifice_si_units
  file_basename: extran3_bottom_orifice_si_units.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Orifices/extran3_bottom_rect_orifice.inp
  network_name: extran3_bottom_rect_orifice
  file_basename: extran3_bottom_rect_orifice.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Orifices/extran3_bottom_rect_orifice_si_units.inp
  network_name: extran3_bottom_rect_orifice_si_units
  file_basename: extran3_bottom_rect_orifice_si_units.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Orifices/extran3_s_curve.inp
  network_name: extran3_s_curve
  file_basename: extran3_s_curve.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Orifices/extran3_side_open_close_orifice.inp
  network_name: extran3_side_open_close_orifice
  file_basename: extran3_side_open_close_orifice.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Orifices/extran3_side_open_close_orifice_si_units.inp
  network_name: extran3_side_open_close_orifice_si_units
  file_basename: extran3_side_open_close_orifice_si_units.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Orifices/extran3_side_open_close_rect_offset_orifice.inp
  network_name: extran3_side_open_close_rect_offset_orifice
  file_basename: extran3_side_open_close_rect_offset_orifice.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Orifices/extran3_side_open_close_rect_offset_orifice_si_units.inp
  network_name: extran3_side_open_close_rect_offset_orifice_si_units
  file_basename: extran3_side_open_close_rect_offset_orifice_si_units.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Orifices/extran3_side_open_close_rect_orifice.inp
  network_name: extran3_side_open_close_rect_orifice
  file_basename: extran3_side_open_close_rect_orifice.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Orifices/extran3_side_open_close_rect_orifice_si_units.inp
  network_name: extran3_side_open_close_rect_orifice_si_units
  file_basename: extran3_side_open_close_rect_orifice_si_units.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Orifices/extran3_side_orifice.inp
  network_name: extran3_side_orifice
  file_basename: extran3_side_orifice.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Orifices/extran3_side_orifice_si_units.inp
  network_name: extran3_side_orifice_si_units
  file_basename: extran3_side_orifice_si_units.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Orifices/extran3_side_rect_orifice
    _si_units.inp
  network_name: extran3_side_rect_orifice _si_units
  file_basename: extran3_side_rect_orifice _si_units.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Orifices/extran3_side_rect_orifice.inp
  network_name: extran3_side_rect_orifice
  file_basename: extran3_side_rect_orifice.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Orifices/extran3_side_rect_orifice_si_units.inp
  network_name: extran3_side_rect_orifice_si_units
  file_basename: extran3_side_rect_orifice_si_units.inp
import_group_id: 8
import_group_name: Model group
cleanup_empty_label_lists: true
validate_after_import: true
run_icm_validation: true
commit_even_if_invalid: false
create_infoworks_shells: true
shell_name_suffix: ''
populate_infoworks_shells: true
