---
import_mode: Batch - Directory Only
base_directory: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models
file_configs:
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/1045_H&H_Elements.inp
  network_name: 1045_H_H_Elements
  file_basename: 1045_H&H_Elements.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/1046_H&H_Elements(1).inp
  network_name: 1046_H_H_Elements_1_
  file_basename: 1046_H&H_Elements(1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/1050_H&H_SI_Units(1).inp
  network_name: 1050_H_H_SI_Units_1_
  file_basename: 1050_H&H_SI_Units(1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/1100_H&H_Elements.inp
  network_name: 1100_H_H_Elements
  file_basename: 1100_H&H_Elements.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/117_H&H_Elements_SI_Units
    (2).inp
  network_name: 117_H_H_Elements_SI_Units _2_
  file_basename: 117_H&H_Elements_SI_Units (2).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/126000_H&H_Elements
    (1).inp
  network_name: 126000_H_H_Elements _1_
  file_basename: 126000_H&H_Elements (1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/126000_H&H_Elements
    (2).inp
  network_name: 126000_H_H_Elements _2_
  file_basename: 126000_H&H_Elements (2).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/1551_H&H_SI_Units_Elements.inp
  network_name: 1551_H_H_SI_Units_Elements
  file_basename: 1551_H&H_SI_Units_Elements.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/1561_H&H_Elements
    (2).inp
  network_name: 1561_H_H_Elements _2_
  file_basename: 1561_H&H_Elements (2).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/1711_H&H_Elements(1).inp
  network_name: 1711_H_H_Elements_1_
  file_basename: 1711_H&H_Elements(1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/1845_H&H_Elements
    (1).inp
  network_name: 1845_H_H_Elements _1_
  file_basename: 1845_H&H_Elements (1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/185_H&H_Elements_SI_Units
    (1).inp
  network_name: 185_H_H_Elements_SI_Units _1_
  file_basename: 185_H&H_Elements_SI_Units (1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/185_H&H_Elements_SI_Units.inp
  network_name: 185_H_H_Elements_SI_Units
  file_basename: 185_H&H_Elements_SI_Units.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/1898_H&H_Elements
    (1).inp
  network_name: 1898_H_H_Elements _1_
  file_basename: 1898_H&H_Elements (1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/193_H&H_SI_Units_Elements(2).inp
  network_name: 193_H_H_SI_Units_Elements_2_
  file_basename: 193_H&H_SI_Units_Elements(2).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/193_H&H_SI_Units_Elements.inp
  network_name: 193_H_H_SI_Units_Elements
  file_basename: 193_H&H_SI_Units_Elements.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/209_H&H_SI_Units
    (2).inp
  network_name: 209_H_H_SI_Units _2_
  file_basename: 209_H&H_SI_Units (2).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/210_H&H_Elements.inp
  network_name: 210_H_H_Elements
  file_basename: 210_H&H_Elements.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/211_H&H_Elements
    (2).inp
  network_name: 211_H_H_Elements _2_
  file_basename: 211_H&H_Elements (2).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/2300_H&H_Elements.inp
  network_name: 2300_H_H_Elements
  file_basename: 2300_H&H_Elements.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/2431_H&H_Elements(2).inp
  network_name: 2431_H_H_Elements_2_
  file_basename: 2431_H&H_Elements(2).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/245_H&H_Si_Units(1).inp
  network_name: 245_H_H_Si_Units_1_
  file_basename: 245_H&H_Si_Units(1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/245_H&H_Si_Units.inp
  network_name: 245_H_H_Si_Units
  file_basename: 245_H&H_Si_Units.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/266_H&H_SI_Unit_Elements(2).inp
  network_name: 266_H_H_SI_Unit_Elements_2_
  file_basename: 266_H&H_SI_Unit_Elements(2).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/266_H&H_SI_Unit_Elements.inp
  network_name: 266_H_H_SI_Unit_Elements
  file_basename: 266_H&H_SI_Unit_Elements.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/270_H&H_Elements(1).inp
  network_name: 270_H_H_Elements_1_
  file_basename: 270_H&H_Elements(1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/2750_H&H_Elements.inp
  network_name: 2750_H_H_Elements
  file_basename: 2750_H&H_Elements.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/296_H&H_Elements(2).inp
  network_name: 296_H_H_Elements_2_
  file_basename: 296_H&H_Elements(2).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/29_H&H_Elements_SI_Units(1).inp
  network_name: 29_H_H_Elements_SI_Units_1_
  file_basename: 29_H&H_Elements_SI_Units(1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/3005_H&H_Elements.inp
  network_name: 3005_H_H_Elements
  file_basename: 3005_H&H_Elements.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/3010_H&H_Elements.inp
  network_name: 3010_H_H_Elements
  file_basename: 3010_H&H_Elements.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/305_H&H_Elements
    (1).inp
  network_name: 305_H_H_Elements _1_
  file_basename: 305_H&H_Elements (1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/305_H&H_Elements(1).inp
  network_name: 305_H_H_Elements_1_
  file_basename: 305_H&H_Elements(1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/305_H&H_Elements.inp
  network_name: 305_H_H_Elements
  file_basename: 305_H&H_Elements.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/314_H&H_Elements(2).inp
  network_name: 314_H_H_Elements_2_
  file_basename: 314_H&H_Elements(2).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/3440_H&H_Elements
    (1).inp
  network_name: 3440_H_H_Elements _1_
  file_basename: 3440_H&H_Elements (1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/35_H&H_Elements_SI_Units(2).inp
  network_name: 35_H_H_Elements_SI_Units_2_
  file_basename: 35_H&H_Elements_SI_Units(2).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/375_H&H_Elements
    (1).inp
  network_name: 375_H_H_Elements _1_
  file_basename: 375_H&H_Elements (1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/375_H&H_Elements(2).inp
  network_name: 375_H_H_Elements_2_
  file_basename: 375_H&H_Elements(2).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/375_H&H_Elements.inp
  network_name: 375_H_H_Elements
  file_basename: 375_H&H_Elements.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/399_H&H_Elements(1).inp
  network_name: 399_H_H_Elements_1_
  file_basename: 399_H&H_Elements(1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/408_H&H_Elements
    (1).inp
  network_name: 408_H_H_Elements _1_
  file_basename: 408_H&H_Elements (1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/408_H&H_Elements(1).inp
  network_name: 408_H_H_Elements_1_
  file_basename: 408_H&H_Elements(1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/43_H&H_Elements
    (1).inp
  network_name: 43_H_H_Elements _1_
  file_basename: 43_H&H_Elements (1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/43_H&H_Elements(1).inp
  network_name: 43_H_H_Elements_1_
  file_basename: 43_H&H_Elements(1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/43a_H&H_Elements(1).inp
  network_name: 43a_H_H_Elements_1_
  file_basename: 43a_H&H_Elements(1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/43a_H&H_Elements(2).inp
  network_name: 43a_H_H_Elements_2_
  file_basename: 43a_H&H_Elements(2).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/43a_H&H_Elements.inp
  network_name: 43a_H_H_Elements
  file_basename: 43a_H&H_Elements.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/443_RDII.inp
  network_name: 443_RDII
  file_basename: 443_RDII.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/4569_Nodes.inp
  network_name: 4569_Nodes
  file_basename: 4569_Nodes.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/470_H&H_Elements(1).inp
  network_name: 470_H_H_Elements_1_
  file_basename: 470_H&H_Elements(1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/470_H&H_Elements.inp
  network_name: 470_H_H_Elements
  file_basename: 470_H&H_Elements.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/476_H&H_Elements(2).inp
  network_name: 476_H_H_Elements_2_
  file_basename: 476_H&H_Elements(2).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/490_KW_H&H_Elements.inp
  network_name: 490_KW_H_H_Elements
  file_basename: 490_KW_H&H_Elements.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/505_H&H_Elements(2).inp
  network_name: 505_H_H_Elements_2_
  file_basename: 505_H&H_Elements(2).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/559_H&H_Elements(2).inp
  network_name: 559_H_H_Elements_2_
  file_basename: 559_H&H_Elements(2).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/590_H&H_Elements.inp
  network_name: 590_H_H_Elements
  file_basename: 590_H&H_Elements.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/6250+H&H_Elements.inp
  network_name: 6250_H_H_Elements
  file_basename: 6250+H&H_Elements.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/630_H&H_Elements
    (1).inp
  network_name: 630_H_H_Elements _1_
  file_basename: 630_H&H_Elements (1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/630_H&H_Elements(2).inp
  network_name: 630_H_H_Elements_2_
  file_basename: 630_H&H_Elements(2).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/633_H&H_Elements(1).inp
  network_name: 633_H_H_Elements_1_
  file_basename: 633_H&H_Elements(1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/7574_H&H_Elements
    (1).inp
  network_name: 7574_H_H_Elements _1_
  file_basename: 7574_H&H_Elements (1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/77_H&H_Elements
    (1).inp
  network_name: 77_H_H_Elements _1_
  file_basename: 77_H&H_Elements (1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/79_Pumps_440_H&H_Elements.inp
  network_name: 79_Pumps_440_H_H_Elements
  file_basename: 79_Pumps_440_H&H_Elements.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/830_H&H_Elements(2).inp
  network_name: 830_H_H_Elements_2_
  file_basename: 830_H&H_Elements(2).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/831_H&H_SI_Units_Elements(1).inp
  network_name: 831_H_H_SI_Units_Elements_1_
  file_basename: 831_H&H_SI_Units_Elements(1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/90_H&H_SI_Units_Elements
    (1).inp
  network_name: 90_H_H_SI_Units_Elements _1_
  file_basename: 90_H&H_SI_Units_Elements (1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/90_H&H_SI_Units_Elements(2).inp
  network_name: 90_H_H_SI_Units_Elements_2_
  file_basename: 90_H&H_SI_Units_Elements(2).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/960_H&H_Elements_SI_Units
    (1).inp
  network_name: 960_H_H_Elements_SI_Units _1_
  file_basename: 960_H&H_Elements_SI_Units (1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/977_H&H_Si_Units_Elements.inp
  network_name: 977_H_H_Si_Units_Elements
  file_basename: 977_H&H_Si_Units_Elements.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/97_H&H_SI_Units_Elements.inp
  network_name: 97_H_H_SI_Units_Elements
  file_basename: 97_H&H_SI_Units_Elements.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/980_H&H_Elements
    (1).inp
  network_name: 980_H_H_Elements _1_
  file_basename: 980_H&H_Elements (1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/Fixed_NEID3_ExistingB&M(1).inp
  network_name: Fixed_NEID3_ExistingB_M_1_
  file_basename: Fixed_NEID3_ExistingB&M(1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/Fixed_NEID3_ExistingB&M(2).inp
  network_name: Fixed_NEID3_ExistingB_M_2_
  file_basename: Fixed_NEID3_ExistingB&M(2).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/H&H_storage_example(2).inp
  network_name: H_H_storage_example_2_
  file_basename: H&H_storage_example(2).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/Merged_Ngf_Airport_10year_mutiple
    nodes.inp
  network_name: Merged_Ngf_Airport_10year_mutiple nodes
  file_basename: Merged_Ngf_Airport_10year_mutiple nodes.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/PCSWMM
    3.2 EXERCISE 1C(1).inp
  network_name: PCSWMM 3_2 EXERCISE 1C_1_
  file_basename: PCSWMM 3.2 EXERCISE 1C(1).inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Semi_Real_Models/culvert_comparison.inp
  network_name: culvert_comparison
  file_basename: culvert_comparison.inp
import_group_id: 6
import_group_name: semi
cleanup_empty_label_lists: true
validate_after_import: true
run_icm_validation: true
commit_even_if_invalid: false
create_infoworks_shells: true
shell_name_suffix: ''
populate_infoworks_shells: true
