---
import_mode: Batch - Directory Only
base_directory: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training
file_configs:
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise0_5_H&H_Elements.inp
  network_name: Exercise0_5_H_H_Elements
  file_basename: Exercise0_5_H&H_Elements.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise0_LID_SUDS_MASTER_FILE.inp
  network_name: Exercise0_LID_SUDS_MASTER_FILE
  file_basename: Exercise0_LID_SUDS_MASTER_FILE.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise0_OutfallBC_65_H_Element.inp
  network_name: Exercise0_OutfallBC_65_H_Element
  file_basename: Exercise0_OutfallBC_65_H_Element.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise0_PID extran_master_swmm34_example_SW5.inp
  network_name: Exercise0_PID extran_master_swmm34_example_SW5
  file_basename: Exercise0_PID extran_master_swmm34_example_SW5.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise0_froude_dampen.inp
  network_name: Exercise0_froude_dampen
  file_basename: Exercise0_froude_dampen.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise0_model_pump_setting.inp
  network_name: Exercise0_model_pump_setting
  file_basename: Exercise0_model_pump_setting.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise0_usgs_5_pollutants.inp
  network_name: Exercise0_usgs_5_pollutants
  file_basename: Exercise0_usgs_5_pollutants.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise1_Continuous_Groundwater.inp
  network_name: Exercise1_Continuous_Groundwater
  file_basename: Exercise1_Continuous_Groundwater.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise1_Cycling_pumps.inp
  network_name: Exercise1_Cycling_pumps
  file_basename: Exercise1_Cycling_pumps.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise1_Horton_Huff_Distribution.inp
  network_name: Exercise1_Horton_Huff_Distribution
  file_basename: Exercise1_Horton_Huff_Distribution.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise1_InflowOrificeRule.inp
  network_name: Exercise1_InflowOrificeRule
  file_basename: Exercise1_InflowOrificeRule.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise1_Many_Flow_Splits.inp
  network_name: Exercise1_Many_Flow_Splits
  file_basename: Exercise1_Many_Flow_Splits.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise1_epaswmm5_tutorial.inp
  network_name: Exercise1_epaswmm5_tutorial
  file_basename: Exercise1_epaswmm5_tutorial.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise1_extran1_KW_Divider.inp
  network_name: Exercise1_extran1_KW_Divider
  file_basename: Exercise1_extran1_KW_Divider.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise1_small_pump_fm_model.inp
  network_name: Exercise1_small_pump_fm_model
  file_basename: Exercise1_small_pump_fm_model.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise1_w_wo_BC_2Subcatchments.inp
  network_name: Exercise1_w_wo_BC_2Subcatchments
  file_basename: Exercise1_w_wo_BC_2Subcatchments.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise2_31_Subs.inp
  network_name: Exercise2_31_Subs
  file_basename: Exercise2_31_Subs.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise2_ALLWEIR.inp
  network_name: Exercise2_ALLWEIR
  file_basename: Exercise2_ALLWEIR.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise2_CS_epaswmm5_tutorial.inp
  network_name: Exercise2_CS_epaswmm5_tutorial
  file_basename: Exercise2_CS_epaswmm5_tutorial.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise2_WestCampusWatershed.inp
  network_name: Exercise2_WestCampusWatershed
  file_basename: Exercise2_WestCampusWatershed.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise2_looped_fm.inp
  network_name: Exercise2_looped_fm
  file_basename: Exercise2_looped_fm.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise2_uphill_example_1.inp
  network_name: Exercise2_uphill_example_1
  file_basename: Exercise2_uphill_example_1.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise2_w_wo_SWALE_2Subcatchments.inp
  network_name: Exercise2_w_wo_SWALE_2Subcatchments
  file_basename: Exercise2_w_wo_SWALE_2Subcatchments.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise3_10_Subs_Continuous.inp
  network_name: Exercise3_10_Subs_Continuous
  file_basename: Exercise3_10_Subs_Continuous.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise3_ALLORF.inp
  network_name: Exercise3_ALLORF
  file_basename: Exercise3_ALLORF.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise3_Clocktime_Pump_Rules.inp
  network_name: Exercise3_Clocktime_Pump_Rules
  file_basename: Exercise3_Clocktime_Pump_Rules.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise3_looped_example_1.inp
  network_name: Exercise3_looped_example_1
  file_basename: Exercise3_looped_example_1.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise3_user5_sub_patterns.inp
  network_name: Exercise3_user5_sub_patterns
  file_basename: Exercise3_user5_sub_patterns.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise3_w_wo_GR_2Subcatchments.inp
  network_name: Exercise3_w_wo_GR_2Subcatchments
  file_basename: Exercise3_w_wo_GR_2Subcatchments.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise4_8_LID_Example_8_Subs.inp
  network_name: Exercise4_8_LID_Example_8_Subs
  file_basename: Exercise4_8_LID_Example_8_Subs.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise4_LID_SI_Units.inp
  network_name: Exercise4_LID_SI_Units
  file_basename: Exercise4_LID_SI_Units.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise4_all_culverts.inp
  network_name: Exercise4_all_culverts
  file_basename: Exercise4_all_culverts.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise4_custom_shapes.inp
  network_name: Exercise4_custom_shapes
  file_basename: Exercise4_custom_shapes.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise4_longFM.inp
  network_name: Exercise4_longFM
  file_basename: Exercise4_longFM.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise4_usgs_miami.inp
  network_name: Exercise4_usgs_miami
  file_basename: Exercise4_usgs_miami.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise5_LID_Pre_Post.inp
  network_name: Exercise5_LID_Pre_Post
  file_basename: Exercise5_LID_Pre_Post.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise5_leaping_weir_2nd.inp
  network_name: Exercise5_leaping_weir_2nd
  file_basename: Exercise5_leaping_weir_2nd.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise5_runoff47_sw5.inp
  network_name: Exercise5_runoff47_sw5
  file_basename: Exercise5_runoff47_sw5.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise5_transect.inp
  network_name: Exercise5_transect
  file_basename: Exercise5_transect.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise6_221_H&H_SI_Units_Elements.inp
  network_name: Exercise6_221_H_H_SI_Units_Elements
  file_basename: Exercise6_221_H&H_SI_Units_Elements.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise6_ALL_Outfall_Types.inp
  network_name: Exercise6_ALL_Outfall_Types
  file_basename: Exercise6_ALL_Outfall_Types.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise6_InfoSewer_ICM.inp
  network_name: Exercise6_InfoSewer_ICM
  file_basename: Exercise6_InfoSewer_ICM.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise6_KW_No_Links_Swmm5_Runoff.inp
  network_name: Exercise6_KW_No_Links_Swmm5_Runoff
  file_basename: Exercise6_KW_No_Links_Swmm5_Runoff.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise6_TunnelMH.inp
  network_name: Exercise6_TunnelMH
  file_basename: Exercise6_TunnelMH.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise6_rtk_long.inp
  network_name: Exercise6_rtk_long
  file_basename: Exercise6_rtk_long.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise7_101_H&H_Elements.inp
  network_name: Exercise7_101_H_H_Elements
  file_basename: Exercise7_101_H&H_Elements.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise7_EPANET_SWMM
    Hazen Williams comparison.inp
  network_name: Exercise7_EPANET_SWMM Hazen Williams comparison
  file_basename: Exercise7_EPANET_SWMM Hazen Williams comparison.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise7_Extran_Master_Hydrology.inp
  network_name: Exercise7_Extran_Master_Hydrology
  file_basename: Exercise7_Extran_Master_Hydrology.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise7_Storage_test_model.inp
  network_name: Exercise7_Storage_test_model
  file_basename: Exercise7_Storage_test_model.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise7_link_seepage.inp
  network_name: Exercise7_link_seepage
  file_basename: Exercise7_link_seepage.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise7_pressure_net.inp
  network_name: Exercise7_pressure_net
  file_basename: Exercise7_pressure_net.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise8_100_Control_Rules.inp
  network_name: Exercise8_100_Control_Rules
  file_basename: Exercise8_100_Control_Rules.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise8_46_pumps.inp
  network_name: Exercise8_46_pumps
  file_basename: Exercise8_46_pumps.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise8_GreenvilleSnowmelt.inp
  network_name: Exercise8_GreenvilleSnowmelt
  file_basename: Exercise8_GreenvilleSnowmelt.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise8_Interceptor.inp
  network_name: Exercise8_Interceptor
  file_basename: Exercise8_Interceptor.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise8_One_Sub_Pump_Model.inp
  network_name: Exercise8_One_Sub_Pump_Model
  file_basename: Exercise8_One_Sub_Pump_Model.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise8_SurchargedWeirs.inp
  network_name: Exercise8_SurchargedWeirs
  file_basename: Exercise8_SurchargedWeirs.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise9_292_Storage_Nodes_200_Subs.inp
  network_name: Exercise9_292_Storage_Nodes_200_Subs
  file_basename: Exercise9_292_Storage_Nodes_200_Subs.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise9_2_Weirs_4Subs.inp
  network_name: Exercise9_2_Weirs_4Subs
  file_basename: Exercise9_2_Weirs_4Subs.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise9_CN_Hydrology.inp
  network_name: Exercise9_CN_Hydrology
  file_basename: Exercise9_CN_Hydrology.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise9_Continuous_Model__WQ.inp
  network_name: Exercise9_Continuous_Model__WQ
  file_basename: Exercise9_Continuous_Model__WQ.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise9_FORCE2.inp
  network_name: Exercise9_FORCE2
  file_basename: Exercise9_FORCE2.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise9_sea_level_pump_model_290_H_Elements.inp
  network_name: Exercise9_sea_level_pump_model_290_H_Elements
  file_basename: Exercise9_sea_level_pump_model_290_H_Elements.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise_40_Subs_327_Links.inp
  network_name: Exercise_40_Subs_327_Links
  file_basename: Exercise_40_Subs_327_Links.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise_PhantomStorage.inp
  network_name: Exercise_PhantomStorage
  file_basename: Exercise_PhantomStorage.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise_SI_PUMP_MID.inp
  network_name: Exercise_SI_PUMP_MID
  file_basename: Exercise_SI_PUMP_MID.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise_Yarra8.inp
  network_name: Exercise_Yarra8
  file_basename: Exercise_Yarra8.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise_singapore.inp
  network_name: Exercise_singapore
  file_basename: Exercise_singapore.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Training/Exercise_siphon_larger_SW5.inp
  network_name: Exercise_siphon_larger_SW5
  file_basename: Exercise_siphon_larger_SW5.inp
import_group_id: 7
import_group_name: test
cleanup_empty_label_lists: true
validate_after_import: true
run_icm_validation: true
commit_even_if_invalid: false
create_infoworks_shells: true
shell_name_suffix: ''
populate_infoworks_shells: true
