---
import_mode: Batch - Directory Only
base_directory: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Pumps
file_configs:
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Pumps/34Pumps.inp
  network_name: 34Pumps
  file_basename: 34Pumps.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Pumps/46_pumps.inp
  network_name: 46_pumps
  file_basename: 46_pumps.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Pumps/extran6_too_many_Ideal_pumps.inp
  network_name: extran6_too_many_Ideal_pumps
  file_basename: extran6_too_many_Ideal_pumps.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Pumps/extran6_type1.inp
  network_name: extran6_type1
  file_basename: extran6_type1.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Pumps/extran6_type1_control_rule.inp
  network_name: extran6_type1_control_rule
  file_basename: extran6_type1_control_rule.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Pumps/extran6_type2.inp
  network_name: extran6_type2
  file_basename: extran6_type2.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Pumps/extran6_type2_control_rule.inp
  network_name: extran6_type2_control_rule
  file_basename: extran6_type2_control_rule.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Pumps/extran6_type2_negative_inverts.inp
  network_name: extran6_type2_negative_inverts
  file_basename: extran6_type2_negative_inverts.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Pumps/extran6_type3.inp
  network_name: extran6_type3
  file_basename: extran6_type3.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Pumps/extran6_type3_control_rule.inp
  network_name: extran6_type3_control_rule
  file_basename: extran6_type3_control_rule.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Pumps/extran6_type4.inp
  network_name: extran6_type4
  file_basename: extran6_type4.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Pumps/extran6_type4_control_rule.inp
  network_name: extran6_type4_control_rule
  file_basename: extran6_type4_control_rule.inp
import_group_id: 8
import_group_name: Model group
cleanup_empty_label_lists: true
validate_after_import: true
run_icm_validation: true
commit_even_if_invalid: false
create_infoworks_shells: true
shell_name_suffix: ''
populate_infoworks_shells: true
