---
import_mode: Batch - Directory Only
base_directory: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Weirs
file_configs:
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Weirs/2_Weirs_4Subs.inp
  network_name: 2_Weirs_4Subs
  file_basename: 2_Weirs_4Subs.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Weirs/extran3_bottom_orifice.inp
  network_name: extran3_bottom_orifice
  file_basename: extran3_bottom_orifice.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Weirs/extran3_bottom_orifice_pid.inp
  network_name: extran3_bottom_orifice_pid
  file_basename: extran3_bottom_orifice_pid.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Weirs/extran3_bottom_orifice_si_units.inp
  network_name: extran3_bottom_orifice_si_units
  file_basename: extran3_bottom_orifice_si_units.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Weirs/extran3_bottom_rect_orifice.inp
  network_name: extran3_bottom_rect_orifice
  file_basename: extran3_bottom_rect_orifice.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Weirs/extran3_bottom_rect_orifice_si_units.inp
  network_name: extran3_bottom_rect_orifice_si_units
  file_basename: extran3_bottom_rect_orifice_si_units.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Weirs/extran3_side_open_close_orifice.inp
  network_name: extran3_side_open_close_orifice
  file_basename: extran3_side_open_close_orifice.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Weirs/extran3_side_open_close_orifice_si_units.inp
  network_name: extran3_side_open_close_orifice_si_units
  file_basename: extran3_side_open_close_orifice_si_units.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Weirs/extran3_side_open_close_rect_offset_orifice.inp
  network_name: extran3_side_open_close_rect_offset_orifice
  file_basename: extran3_side_open_close_rect_offset_orifice.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Weirs/extran3_side_open_close_rect_offset_orifice_si_units.inp
  network_name: extran3_side_open_close_rect_offset_orifice_si_units
  file_basename: extran3_side_open_close_rect_offset_orifice_si_units.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Weirs/extran3_side_open_close_rect_orifice.inp
  network_name: extran3_side_open_close_rect_orifice
  file_basename: extran3_side_open_close_rect_orifice.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Weirs/extran3_side_open_close_rect_orifice_si_units.inp
  network_name: extran3_side_open_close_rect_orifice_si_units
  file_basename: extran3_side_open_close_rect_orifice_si_units.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Weirs/extran3_side_orifice.inp
  network_name: extran3_side_orifice
  file_basename: extran3_side_orifice.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Weirs/extran3_side_orifice_si_units.inp
  network_name: extran3_side_orifice_si_units
  file_basename: extran3_side_orifice_si_units.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Weirs/extran3_side_rect_orifice
    _si_units.inp
  network_name: extran3_side_rect_orifice _si_units
  file_basename: extran3_side_rect_orifice _si_units.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Weirs/extran3_side_rect_orifice.inp
  network_name: extran3_side_rect_orifice
  file_basename: extran3_side_rect_orifice.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Weirs/extran4.inp
  network_name: extran4_2
  file_basename: extran4.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Weirs/extran4_no_surcharge.inp
  network_name: extran4_no_surcharge
  file_basename: extran4_no_surcharge.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Weirs/extran4_roadway.inp
  network_name: extran4_roadway
  file_basename: extran4_roadway.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Weirs/extran4_sideflow.inp
  network_name: extran4_sideflow
  file_basename: extran4_sideflow.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Weirs/extran4_trapezoidal.inp
  network_name: extran4_trapezoidal
  file_basename: extran4_trapezoidal.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Weirs/extran4_vnotch.inp
  network_name: extran4_vnotch
  file_basename: extran4_vnotch.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Weirs/v14RTCManyRules.inp
  network_name: v14RTCManyRules
  file_basename: v14RTCManyRules.inp
import_group_id: 8
import_group_name: Model group
cleanup_empty_label_lists: true
validate_after_import: true
run_icm_validation: true
commit_even_if_invalid: false
create_infoworks_shells: true
shell_name_suffix: ''
populate_infoworks_shells: true
