---
import_mode: Batch - Directory Only
base_directory: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Greenville
file_configs:
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Greenville/Greenville_all_SWMM5_Features.inp
  network_name: Greenville_all_SWMM5_Features
  file_basename: Greenville_all_SWMM5_Features.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Greenville/Greenville_all_SWMM5_Features_SI_Units.inp
  network_name: Greenville_all_SWMM5_Features_SI_Units
  file_basename: Greenville_all_SWMM5_Features_SI_Units.inp
- file_path: C:/Users/rober/GitHub/1729-SWMM5-Models-2030/Greenville/Greenville_small_snowmelt_model.inp
  network_name: Greenville_small_snowmelt_model
  file_basename: Greenville_small_snowmelt_model.inp
import_group_id: 16
import_group_name: user4
cleanup_empty_label_lists: true
validate_after_import: true
run_icm_validation: true
commit_even_if_invalid: false
create_infoworks_shells: true
shell_name_suffix: ''
